-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 20:51:34 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gift_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gift_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gift_management` DEFAULT CHARACTER SET utf8 ;
USE `gift_management` ;

-- -----------------------------------------------------
-- Table `gift_management`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`user` (
  `id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL DEFAULT '账号4-15数字字母任意组合',
  `password` VARCHAR(45) NULL DEFAULT '密码',
  `email` VARCHAR(45) NULL DEFAULT '邮箱',
  `phone` VARCHAR(45) NULL DEFAULT '手机号',
  `role` INT NULL DEFAULT '角色身份id',
  `create_time` DATETIME NULL DEFAULT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`gift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`gift` (
  `id` INT NOT NULL DEFAULT 礼品id,
  `groupid` TEXT(1000) NULL DEFAULT '仅针对组合商品，33*2,34*4. 单品次字段为‘’',
  `type` INT NULL DEFAULT 'dim表id',
  `classify_id` INT NULL DEFAULT 商品分类id,
  `brand_id` INT NULL DEFAULT 商品品牌id,
  `supply_id` INT NULL DEFAULT 商品供应商id,
  `sale_price` FLOAT NULL DEFAULT 销售价格,
  `buy_price` FLOAT NULL DEFAULT 采购价格,
  `store_num` INT NULL DEFAULT 库存,
  `munit` VARCHAR(45) NULL DEFAULT '商品计量单位',
  `deliver_id` INT NULL DEFAULT 快递id,
  `desciption` TEXT(1000) NULL DEFAULT '商品描述',
  `pic_ids` VARCHAR(255) NULL DEFAULT '宣传图片id，用逗号的拼接列表',
  `remark` TEXT(1000) NULL DEFAULT '备注',
  `status` INT NULL DEFAULT 状态 1: 上架， 2 下架,
  `ctime` DATETIME NULL DEFAULT 创建时间,
  `utime` DATETIME NULL DEFAULT 更新时间,
  `sold_num` INT NULL DEFAULT 售出数量，初始为0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`dim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`dim` (
  `id` INT NOT NULL,
  `dim_type` VARCHAR(45) NULL DEFAULT '维度类型，gift_type: 商品类型，deliver:快递列表 3: wechat_style',
  `dim_value` VARCHAR(45) NULL DEFAULT '维度值',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`media` (
  `id` INT NOT NULL DEFAULT id,
  `path` VARCHAR(255) NULL DEFAULT '存储路径' COMMENT '包括商品图片，多媒体管理里面的图片／视频／音频',
  `name` VARCHAR(45) NULL DEFAULT '名称',
  `status` INT NULL DEFAULT 1:停用 2启用,
  `ctime` DATETIME NULL DEFAULT 创建时间,
  `utime` DATETIME NULL DEFAULT 更新时间,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`gift_his`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`gift_his` (
  `id` INT NOT NULL,
  `oper_type` INT NULL DEFAULT 1: 新建 2: 编辑 3:出库 4: 入库 COMMENT '保存操作后，gift表的信息',
  `gift_id` INT NULL DEFAULT 礼品id,
  `groupid` TEXT(1000) NULL DEFAULT '仅针对组合商品，33*2,34*4. 单品次字段为‘’',
  `type` INT NULL DEFAULT 'dim表id',
  `classify_id` INT NULL DEFAULT 商品分类id,
  `brand_id` INT NULL DEFAULT 商品品牌id,
  `sale_price` FLOAT NULL DEFAULT 销售价格,
  `supply_id` INT NULL DEFAULT 商品供应商id,
  `buy_price` FLOAT NULL DEFAULT 采购价格,
  `store_num` INT NULL DEFAULT 库存,
  `deliver_id` INT NULL DEFAULT 快递id,
  `munit` VARCHAR(45) NULL DEFAULT '商品计量单位',
  `desciption` TEXT(1000) NULL DEFAULT '商品描述',
  `pic_ids` VARCHAR(255) NULL DEFAULT '宣传图片id，用逗号的拼接列表',
  `remark` TEXT(1000) NULL DEFAULT '备注',
  `ctime` DATETIME NULL DEFAULT 创建时间,
  `status` INT NULL DEFAULT 状态 1: 上架， 2 下架,
  `utime` DATETIME NULL DEFAULT 更新时间,
  `sold_num` INT NULL DEFAULT 售出数量，初始为0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`gift_classify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`gift_classify` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT '分类名称',
  `status` INT NULL DEFAULT 1:启用 2:停用,
  `remark` TEXT(1000) NULL DEFAULT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`gift_brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`gift_brand` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT '品牌名称',
  `status` INT NULL DEFAULT 1:启用 2:停用,
  `remark` TEXT(1000) NULL DEFAULT '备注'),
  PRIMARY KEY (`id`)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`gift_supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`gift_supply` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT '品牌名称',
  `status` INT NULL DEFAULT 1:启用 2:停用,
  `remark` TEXT(1000) NULL DEFAULT '备注',
  `contact_person` VARCHAR(45) NULL DEFAULT '联系人',
  `phone` VARCHAR(45) NULL DEFAULT '手机号',
  `qq` VARCHAR(45) NULL DEFAULT 'qq号',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`gift_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`gift_book` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT '礼册名称',
  `theme_id` INT NULL DEFAULT 礼册主题id,
  `set_id` INT NULL DEFAULT 礼册系列id,
  `wechat_id` INT NULL DEFAULT 微信模版id,
  `type_id` INT NULL DEFAULT 礼册类型id 1: 普通 2: 年卡 3: 半年卡 4:季卡,
  `sale_price` FLOAT NULL DEFAULT 销售价格,
  `group_ids` VARCHAR(255) NULL DEFAULT '33*3,34*2',
  `describe` TEXT(1000) NULL DEFAULT '礼册描述',
  `pic_id` INT NULL DEFAULT 上传后，需要保存到 media表,
  `remark` TEXT(1000) NULL DEFAULT '备注',
  `status` INT NULL DEFAULT 1: 启用 2: 停用,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`gift_book_his`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`gift_book_his` (
  `id` INT NOT NULL,
  `gift_book_id` INT NULL DEFAULT 礼册id,
  `type` VARCHAR(45) NULL DEFAULT '1: 新建 2: 编辑，3: 停用，4:启用',
  `name` VARCHAR(45) NULL DEFAULT '礼册名称',
  `theme_id` INT NULL DEFAULT 礼册主题id,
  `set_id` INT NULL DEFAULT 礼册系列id,
  `wechat_id` INT NULL DEFAULT 微信模版id,
  `type_id` INT NULL DEFAULT 礼册类型id 1: 普通 2: 年卡 3: 半年卡 4:季卡,
  `group_ids` VARCHAR(255) NULL DEFAULT '33*3,34*2',
  `sale_price` FLOAT NULL DEFAULT 销售价格,
  `describe` TEXT(1000) NULL DEFAULT '礼册描述',
  `pic_id` INT NULL DEFAULT 上传后，需要保存到 media表,
  `remark` TEXT(1000) NULL DEFAULT '备注',
  `status` INT NULL DEFAULT 1: 启用 2: 停用,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`theme` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `remark` TEXT(1000) NULL,
  `status` INT NULL DEFAULT 1: 启用 2: 停用,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`set` (
  `id` INT NOT NULL COMMENT '系列',
  `name` VARCHAR(45) NULL,
  `remark` TEXT(1000) NULL,
  `status` INT NULL DEFAULT 1: 启用 2: 停用)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`gift_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`gift_card` (
  `id` INT NOT NULL DEFAULT id,
  `num_code` INT NULL DEFAULT 礼品卡号码,
  `passwod` INT NULL DEFAULT 密码,
  `ctime` VARCHAR(45) NULL DEFAULT '生成时间',
  `status` INT NULL DEFAULT 状态 1: 未激活 2: 已激活 3:已启用 4: 已过期 5: 已退卡 6: 冻结,
  `book_id` INT NULL DEFAULT 礼册id,
  `discount` FLOAT NULL DEFAULT 折扣 0-10,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`card_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`card_order` (
  `id` INT NOT NULL,
  `sales_id` INT NULL DEFAULT '销售员id，从user表获取',
  `custom_id` INT NULL DEFAULT 客户id，从客户表取,
  `delever_id` INT NULL DEFAULT 快递公司id,
  `expire_date` DATETIME NULL DEFAULT 失效日期,
  `wechat_id` INT NULL DEFAULT 微信模版id,
  `remark` TEXT(1000) NULL DEFAULT '备注',
  `delivrer_num` VARCHAR(45) NULL DEFAULT '快递单号',
  `order_name` VARCHAR(45) NULL DEFAULT '册1*2，册2*3',
  `status` INT NULL DEFAULT 1:待审核 2: 待发货 3: 已完成 4作废,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`map_order_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`map_order_card` (
  `id` INT NOT NULL,
  `order_id` INT NULL DEFAULT 订单id,
  `card_id` INT NULL DEFAULT 礼品卡id,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`change_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`change_order` (
  `id` INT NOT NULL,
  `card_id` INT NOT NULL,
  `card_num` VARCHAR(45) NOT NULL,
  `gift_id` INT NULL DEFAULT 选择兑换的商品id,
  `customer_name` VARCHAR(45) NULL DEFAULT '用户名称，收件人',
  `photo` VARCHAR(45) NULL DEFAULT '电话',
  `address` VARCHAR(255) NULL DEFAULT '收件地址',
  `post_code` VARCHAR(45) NULL DEFAULT '邮编',
  `deliver_id` INT NULL DEFAULT 快递公司id,
  `deliver_date` DATETIME NULL DEFAULT 发货日期,
  `remark` TEXT(1000) NULL DEFAULT '备注',
  `status` INT NULL DEFAULT 订单状态,
  `deliver_num` VARCHAR(45) NULL DEFAULT '快递单号',
  `order_source` INT NULL DEFAULT 订单来源，1: 电话，2: 官网，3:微信,
  PRIMARY KEY (`id`, `card_id`, `card_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT '客户名称',
  `type` INT NULL DEFAULT 1:代理商 2:企业大客户,
  `contact_person` VARCHAR(45) NULL DEFAULT '联系人',
  `phone` VARCHAR(45) NULL DEFAULT '手机号',
  `address` VARCHAR(45) NULL DEFAULT '地址',
  `status` INT NULL DEFAULT 1: 启用 2:停用,
  `ctime` DATETIME NULL DEFAULT 创建时间,
  `utime` DATETIME NULL DEFAULT 更新时间 COMMENT '客户表',
  `email` VARCHAR(45) NULL DEFAULT '邮箱',
  `postcode` VARCHAR(45) NULL DEFAULT '邮编',
  `remark` TEXT(1000) NULL DEFAULT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`website`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`website` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT '网站名称',
  `type` INT NULL DEFAULT 1:兑换网站 2:礼册商城,
  `domain` VARCHAR(45) NULL DEFAULT '绑定域名',
  `hotline` VARCHAR(45) NULL DEFAULT '客服热线',
  `qq` VARCHAR(45) NULL DEFAULT 'qq号码',
  `expire_time` DATETIME NULL DEFAULT 有效期,
  `pic_id` INT NULL DEFAULT log id，来自呀media表,
  `describe` TEXT(1000) NULL DEFAULT '描述',
  `remark` VARCHAR(45) NULL DEFAULT '备注',
  `status` INT NULL DEFAULT 1: 启用 2:停用,
  `ctime` DATETIME NULL DEFAULT 创建时间 COMMENT '	',
  `utime` DATETIME NULL DEFAULT 更新时间 COMMENT '	',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gift_management`.`wechat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gift_management`.`wechat` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT '模版名称' COMMENT '	',
  `style` INT NULL DEFAULT 样式，从dim 取wechat_style,
  `pic_id` INT NULL DEFAULT 图片id,
  `autio_id` VARCHAR(45) NULL DEFAULT '音频id',
  `vedio_id` VARCHAR(45) NULL DEFAULT '视频id',
  `copywriter` TEXT(1000) NULL DEFAULT '文案',
  `url` VARCHAR(255) NULL DEFAULT '网址',
  `expire_time` DATETIME NULL DEFAULT 有效期,
  `status` INT NULL DEFAULT 1: 启用 2:停用,
  `remark` TEXT(1000) NULL DEFAULT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
